version: '3.8'

services:
  keydb:
    image: eqalpha/keydb:latest
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  web:
    restart: always
    build: ./app
    command: gunicorn hello_django.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --reload  # python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    environment:
      - MIGRATE_HERE=1
    depends_on:
      - db
      - keydb
  celery:
    build: ./app
    command: celery --app=hello_django worker --loglevel=INFO --logfile=logs/celery.log
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - keydb
  celery-beat:
    build: ./app
    command: celery --app=hello_django beat --loglevel=INFO --logfile=logs/celery-beat.log
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - web
      - keydb
      - celery

volumes:
  postgres_data: