# Generated by Django 4.0.2 on 2022-03-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users_count',
            field=models.IntegerField(null=True),
        ),
    ]
